services:
  - type: web
    name: mysql
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: G12345J
      - key: MYSQL_DATABASE
        value: rec_sys
    autoDeploy: false
    healthCheckPath: ""  # disables HTTP health check to prevent timeout    autoDeploy: false
